//! Tricky kondo-parity cases found while diffing against the JVM oracle.
use nx_core::analyzer::*;
use nx_core::intern;

fn run(src: &str, kind: FileKind) -> FileAnalysis {
    let cfg = Config::new();
    let mut defs = DefsIndex::new();
    let mut fa = analyze_file(src, kind, &cfg, &defs);
    defs.add_file(&fa);
    finish_usages(&mut fa, &defs);
    fa
}
fn clj(src: &str) -> FileAnalysis {
    run(src, FileKind::Clj)
}
fn usages<'a>(fa: &'a FileAnalysis, name: &str) -> Vec<&'a VarUsage> {
    fa.var_usages.iter().filter(|u| u.name.as_str() == name).collect()
}

#[test]
fn hof_registers_two_usages_second_without_name_position() {
    let fa = clj("(ns a)\n(defn f [xs] (map inc xs))");
    let u = usages(&fa, "inc");
    assert_eq!(u.len(), 2);
    let plain = u.iter().find(|x| x.arity == NO_ARITY).unwrap();
    let hof = u.iter().find(|x| x.arity == 1).unwrap();
    assert!(plain.name_pos.row != 0);
    assert_eq!(hof.name_pos.row, 0, "hof-call name has no metadata in kondo");
    assert_eq!(hof.pos, plain.pos);
    assert_eq!(hof.to, intern("clojure.core"));
}

#[test]
fn syntax_quote_gensym_is_unresolved_usage() {
    let fa = clj("(ns a)\n(defmacro m [x] `(let [y# ~x] y#))");
    let u = usages(&fa, "y#");
    assert_eq!(u.len(), 2);
    assert!(u.iter().all(|x| x.to == intern("clj-kondo/unknown-namespace")));
}

#[test]
fn threading_uses_form_positions_and_generated_calls_have_none() {
    let fa = clj("(ns a)\n(defn f [x] (-> x (assoc :a 1)) (cond-> x true inc))");
    let assoc = usages(&fa, "assoc")[0];
    assert_eq!(assoc.arity, 3); // threaded arg counts
    assert_eq!((assoc.pos.row, assoc.pos.col), (2, 19)); // position of `(assoc :a 1)`
    // `let`/`if` generated by cond-> carry no position at all
    let l = usages(&fa, "let");
    assert!(l.iter().any(|u| u.pos.row == 0 && u.name_pos.row == 0));
}

#[test]
fn fn_literal_params_and_percent() {
    let fa = clj("(ns a)\n(defn f [xs] (map #(inc %) xs))");
    let f = usages(&fa, "fn*");
    assert_eq!(f.len(), 1);
    assert!(f[0].pos.row != 0 && f[0].name_pos.row == 0);
    // `%` is a pseudo binding: a usage without id and name; `%1` params register no local
    assert!(fa.local_usages.iter().any(|u| u.id == 0 && u.name.is_none()));
    assert!(fa.locals.iter().all(|l| l.name.as_str() != "%1"));
}

#[test]
fn type_hint_is_a_nameless_local_usage() {
    let fa = clj("(ns a)\n(defn f [^long x] x)");
    let hint: Vec<_> = fa.local_usages.iter().filter(|u| u.id == 0).collect();
    assert_eq!(hint.len(), 1);
    assert!(hint[0].name.is_none());
}

#[test]
fn deftest_is_defn_with_test_flag_and_callstack() {
    let fa = clj("(ns a (:require [clojure.test :refer [deftest is]]))\n(deftest t (is (= 1 1)))");
    let d = fa.var_definitions.iter().find(|d| d.name.as_str() == "t").unwrap();
    assert!(d.test);
    assert_eq!(d.defined_by, (intern("clojure.test"), intern("deftest")));
    assert_eq!(fa.callstacks[d.cs.0 as usize], (intern("clojure.test"), intern("deftest")));
    let refer = fa.var_usages.iter().filter(|u| u.refer).count();
    assert_eq!(refer, 2);
}

#[test]
fn catch_without_body_has_null_scope_end() {
    let fa = clj("(ns a)\n(try 1 (catch Exception _))");
    let l = fa.locals.iter().find(|l| l.name.as_str() == "_").unwrap();
    assert_eq!(l.scope_end_row, u32::MAX);
}

#[test]
fn namespace_usage_alias_and_prefix_lists() {
    let fa = clj("(ns a (:require [clojure [string :as s] [set]] [b]))");
    let to: Vec<_> = fa.namespace_usages.iter().map(|u| u.to.as_str()).collect();
    assert_eq!(to, ["clojure.string", "clojure.set", "b"]);
    assert_eq!(fa.namespace_usages[0].alias.as_str(), "s");
    assert!(fa.namespace_usages[1].alias.is_none());
}

#[test]
fn meta_clause_on_ns_require_is_unwrapped() {
    let fa = clj("(ns a\n  ^{:added \"1\"} (:require [b]))");
    assert_eq!(fa.namespace_usages.len(), 1);
}

#[test]
fn meta_arglists_and_arglist_strs_ignore_type_hints() {
    let fa = clj("(ns a)\n(defn ^:private f [^String s & more] s)\n(def ^{:arglists '([x])} g (fn [y] y))");
    let f = fa.var_definitions.iter().find(|d| d.name.as_str() == "f").unwrap();
    assert!(f.private);
    assert_eq!(fa.strs[f.arglists.0 as usize].as_str(), "[s & more]");
    assert_eq!(f.varargs_min, 1);
    let g = fa.var_definitions.iter().find(|d| d.name.as_str() == "g").unwrap();
    assert_eq!(fa.strs[g.arglists.0 as usize].as_str(), "[x]");
    assert_eq!(g.meta.0.as_str(), "{\"arglists\":[\"quote\",[[\"x\"]]]}");
}

#[test]
fn def_of_fn_gets_arities_but_def_of_value_does_not() {
    let fa = clj("(ns a)\n(def f (fn [a] a))\n(def v 1)");
    let f = fa.var_definitions.iter().find(|d| d.name.as_str() == "f").unwrap();
    assert!(f.has_fixed && f.fixed.has(1));
    let v = fa.var_definitions.iter().find(|d| d.name.as_str() == "v").unwrap();
    assert!(!v.has_fixed);
}

#[test]
fn lint_as_defaults_go_loop_is_loop() {
    let fa = clj("(ns a (:require [clojure.core.async :as a]))\n(defn f [] (a/go-loop [x 1] (recur x)))");
    assert!(fa.locals.iter().any(|l| l.name.as_str() == "x"));
}

#[test]
fn defmethod_dispatch_value_and_flag() {
    let fa = clj("(ns a)\n(defmulti m :k)\n(defmethod m :x [_] 1)");
    let u = usages(&fa, "m");
    assert_eq!(u.len(), 1);
    assert!(u[0].defmethod);
    assert_eq!(u[0].dispatch_val_str.as_str(), ":x");
}

#[test]
fn core_special_forms_have_override_info() {
    let fa = clj("(ns a)\n(def x 1)\n(set! *warn-on-reflection* true)");
    let d = usages(&fa, "def")[0];
    assert!(d.macro_ && d.fixed.has(1) && d.fixed.has(3));
    let s = usages(&fa, "set!")[0];
    assert!(s.macro_ && s.fixed.has(2));
}

#[test]
fn unloaded_namespace_has_no_target_info_when_only_used_in_try_body() {
    // kondo drops results of a `try` body, so a namespace used only there is never loaded from cache
    let cfg = Config::new();
    let mut defs = DefsIndex::new();
    defs.add_jar_var(Src::Clj, intern("lib.core"), intern("f"), VarInfo { flags: defs::F_FIXED, varargs_min: NO_ARITY, fixed: { let mut a = Arities::default(); a.add(1); a }, deprecated: Val::NONE });
    let mut fa = analyze_file("(ns a (:require [lib.core :as l]))\n(defn g [] (try (l/f 1) (catch Exception _ nil)))", FileKind::Clj, &cfg, &defs);
    defs.add_file(&fa);
    finish_usages(&mut fa, &defs);
    let u = usages(&fa, "f")[0];
    assert!(!u.has_fixed);
    assert_eq!(u.to, intern("lib.core"));
    // used outside try: info is loaded
    let mut fb = analyze_file("(ns b (:require [lib.core :as l]))\n(defn g [] (l/f 1))", FileKind::Clj, &cfg, &defs);
    defs.add_file(&fb);
    finish_usages(&mut fb, &defs);
    assert!(usages(&fb, "f")[0].has_fixed);
}

#[test]
fn cljc_is_analyzed_once_per_language_with_reader_conditionals_resolved() {
    let fa = run("(ns a)\n#?(:clj (defn f [x] x) :cljs (defn g [x] x))\n(defn both [] 1)", FileKind::Cljc);
    let names: Vec<(String, u8)> = fa.var_definitions.iter().map(|d| (d.name.as_str().to_owned(), d.lang)).collect();
    assert!(names.contains(&("f".into(), L_CLJ)));
    assert!(names.contains(&("g".into(), L_CLJS)));
    assert!(!names.contains(&("f".into(), L_CLJS)));
    assert_eq!(names.iter().filter(|n| n.0 == "both").count(), 2);
    assert_eq!(fa.namespace_definitions.len(), 2);
}

#[test]
fn hook_with_temp_dir_expands_to_let_without_from_var() {
    let mut cfg = Config::new();
    cfg.merge_edn("{:hooks {:analyze-call {babashka.fs/with-temp-dir babashka.fs/with-temp-dir}}}");
    let mut defs = DefsIndex::new();
    let mut fa = analyze_file("(ns a (:require [babashka.fs :as fs]))\n(defn f [] (fs/with-temp-dir [d {}] (str d)))", FileKind::Clj, &cfg, &defs);
    defs.add_file(&fa);
    finish_usages(&mut fa, &defs);
    let orig = usages(&fa, "with-temp-dir")[0];
    assert!(orig.from_var.is_none());
    let l = usages(&fa, "let")[0];
    assert!(l.derived && l.derived_name);
    assert!(fa.locals.iter().any(|l| l.name.as_str() == "d"));
}

/// `NX_FUZZ_DIR=<dir> cargo test --release -- --ignored fuzz_truncation`: analyzing truncated sources must not panic.
#[test]
#[ignore]
fn fuzz_truncation() {
    let Ok(dir) = std::env::var("NX_FUZZ_DIR") else { return };
    fn walk(d: &std::path::Path, o: &mut Vec<std::path::PathBuf>) {
        if let Ok(rd) = std::fs::read_dir(d) {
            for e in rd.flatten() {
                let p = e.path();
                if p.is_dir() {
                    walk(&p, o);
                } else if FileKind::from_path(&p.to_string_lossy()).map_or(false, |k| k != FileKind::Edn) {
                    o.push(p);
                }
            }
        }
    }
    let mut files = Vec::new();
    walk(std::path::Path::new(&dir), &mut files);
    let cfg = Config::new();
    let defs = DefsIndex::new();
    let mut n = 0;
    for p in files {
        let Ok(text) = std::fs::read_to_string(&p) else { continue };
        let kind = FileKind::from_path(&p.to_string_lossy()).unwrap();
        let len = text.len();
        for frac in [3usize, 7, 13, 29] {
            let mut cut = len * frac / 31;
            while !text.is_char_boundary(cut) {
                cut -= 1;
            }
            let t = &text[..cut];
            if std::env::var("NX_FUZZ_V").is_ok() {
                eprintln!("{} {}", p.display(), cut);
            }
            let r = std::panic::catch_unwind(|| {
                let fa = analyze_file(t, kind, &cfg, &defs);
                let _ = emit::to_json("x", "clj", &fa);
            });
            assert!(r.is_ok(), "panic on {} cut at {}", p.display(), cut);
            n += 1;
        }
        // delete a few bytes in the middle (deterministic)
        let mut seed = len as u64 * 2654435761 + 1;
        for _ in 0..4 {
            seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            let mut a = (seed >> 33) as usize % len.max(1);
            while !text.is_char_boundary(a) {
                a -= 1;
            }
            let mut b = (a + 1 + (seed >> 20) as usize % 12).min(len);
            while !text.is_char_boundary(b) {
                b += 1;
            }
            let t = format!("{}{}", &text[..a], &text[b..]);
            let r = std::panic::catch_unwind(|| {
                let fa = analyze_file(&t, kind, &cfg, &defs);
                let _ = emit::to_json("x", "clj", &fa);
            });
            assert!(r.is_ok(), "panic on {} deleting {}..{}", p.display(), a, b);
            n += 1;
        }
    }
    eprintln!("fuzzed {} inputs", n);
}
