//! Pending-conformance harness: the debt ledger for behavior mova does
//! **not** yet implement. Sibling to `tests/conformance_test.rs` (the
//! "already conforms" ledger), this one is the mirror image: every form
//! under `tests/conformance/pending/*.corpus` is expected to *diverge*
//! from real Clojure 1.13.0-alpha6 today, and the whole point of running
//! it is to keep that claim honest -- a pending form that starts
//! conforming (mova got fixed, or the form was too weak to prove
//! anything) must be caught and promoted out, the same way
//! `conformance_test.rs` catches a stale `DEVIATIONS.md` entry.
//!
//! # Format
//!
//! For an area `<area>` under `tests/conformance/pending/`:
//!
//! - `<area>.corpus` -- one form per line; `;;`-prefixed and blank lines
//!   skipped (identical rules to `tests/conformance_test.rs::is_skippable`).
//! - `<area>.golden` -- one line per form, from REAL Clojure
//!   1.13.0-alpha6 (see `tests/conformance/CLOJURE_VERSION`), generated by
//!   `tools/jvm-pending-runner.clj` via `tools/gen-pending.sh`:
//!   `OK<TAB><pr-str>` or `ERR<TAB><ExceptionSimpleName>`. Note the format
//!   difference from the main corpus's bare `ERR`: pending goldens keep
//!   Clojure's exception class around so a future error-taxonomy pass has
//!   something to build on, even though this driver does not compare
//!   exception identity yet (see `ErrBoth` below).
//! - `<area>.mova` -- one line per form, mova's CURRENT behavior, in the
//!   SAME `OK<TAB>.. / ERR<TAB><first-line> / TIMEOUT` shape. Regenerated
//!   by `tools/gen-pending.sh`. **Documentation only** -- this driver
//!   never reads it and never fails because it went stale; it exists so a
//!   human (or the next area-writing agent) can `git diff` mova's error
//!   text changing without re-running anything.
//!
//! # Session model: ONE process per area file, matching the golden side
//!
//! `tests/conformance_test.rs` gives each corpus *file* one `Interp`, and
//! `tools/jvm-pending-runner.clj` (the golden generator) gives each area
//! file one real-JVM Clojure session the same way -- a `def` on line 3 is
//! visible to a form on line 7. An earlier revision of this driver ran
//! **one fresh `mova -e` process per form** instead, for hang-safety
//! reasons (see below); that was a real correctness bug, not a harmless
//! simplification: several areas (`records`, `protocols`, `metadata`,
//! `multimethods`, `vars-binding`, `namespaces`, `state`, ...) are
//! written assuming session state carries across lines, so per-form
//! isolation was reporting `ERR unresolved symbol` for forms whose real
//! mova behavior (with the `def` actually in scope) could be a value that
//! matches Clojure's golden exactly -- a harness artifact silently
//! reported as mova's behavior, capable of hiding a genuine `Conform`
//! behind a fake `Diverge`/`ErrBoth`. A ledger that can't detect a
//! paid-off debt defeats the entire point of this directory.
//!
//! This driver now runs each area file as **one `mova <script>`
//! process**: `build_session_script` compiles every form in the file into
//! ONE generated mova program (forms embedded as string literals,
//! evaluated via `(eval (read-string ...))` -- the same technique
//! `tools/jvm-pending-runner.clj` uses on the golden side, so a
//! deliberately-malformed form, which `reader.corpus` exists to probe,
//! can never corrupt the surrounding wrapper's own parens the way
//! splicing raw source would). Each form is wrapped in mova's untyped
//! `try`/`catch` and prints a tagged `##PENDING-{BEGIN,OK,ERR}##<index>`
//! marker line, so one form throwing can never stop the forms after it
//! (mirroring `jvm-pending-runner.clj`'s own per-form `catch Throwable`
//! inside its `doseq`) -- only a genuine hang or a process crash can
//! still end the session early, which is exactly what `run_session`'s
//! per-file timeout and the `Timeout`/`Unreached` classifications below
//! exist to bound and report rather than silently lose. stdout AND
//! stderr are merged into one captured file (two independent
//! `File::try_clone` handles sharing one fd, the same trick a shell's
//! `2>&1` uses) so a crash diagnostic -- which mova writes to stderr, not
//! stdout -- is never silently dropped; a previous run in this campaign
//! lost an entire session's diagnostics by only capturing stdout.
//!
//! Hang safety is why this is a process boundary at all rather than an
//! in-process `Engine`: mova has a known bug where a non-tail `recur`
//! loops forever, and pending forms deliberately probe for it
//! (`errors.corpus`'s last form). `run_session` polls `try_wait` and
//! kills the child after `file_timeout(forms.len())` rather than
//! blocking on `wait()`, which would hang this test process right along
//! with a stuck child.
//!
//! `errors.corpus` deliberately places its hanging form LAST in the file
//! (as of this writing, form 18 of 18) specifically so that nothing in
//! that file is `Unreached` today -- putting a hang mid-file would blind
//! the ledger to every real form after it. That placement is a
//! corpus-authoring convention, not something this driver enforces
//! structurally; the `Unreached` count in the per-area summary is what
//! polices it going forward -- a nonzero `Unreached` total for an area
//! that isn't deliberately testing early termination is a sign a hang (or
//! a crash) landed somewhere other than the end of that file.
//!
//! # Classification
//!
//! - **`Conform`** -- Clojure's golden is `OK v` and mova also returns
//!   `OK v` with the byte-identical printed value. This is the one
//!   outcome that must never pass quietly: it means the "pending" form
//!   isn't pending anymore. **Fails the test**, naming file, line, form,
//!   and the promotion instruction.
//! - **`ErrBoth`** -- both sides threw. Provisional and **never**
//!   auto-promoted: mova has no exception-class taxonomy yet, so "both
//!   threw" does not prove the same thing was thrown. Counted and
//!   reported separately as "needs error taxonomy".
//! - **`Diverge`** -- anything else (`OK` vs `ERR`, or `OK` with a
//!   different printed value on each side). The expected, healthy state.
//! - **`Timeout`** -- the form whose `##PENDING-BEGIN##<i>` marker was
//!   the last one seen before the session ended early (killed after
//!   `file_timeout`, or the process crashed) with no matching `OK`/`ERR`
//!   marker for it. A real, known failure mode (non-tail `recur` loops
//!   forever in mova today) that pending forms deliberately probe for.
//!   Reported as its own bucket, EXCLUSIVE of `Diverge` -- a hang is a
//!   materially worse failure than a wrong answer, so it is never folded
//!   into the `Diverge` count (it can never satisfy `Conform` either,
//!   since `Conform` requires a successful, value-matching `OK`). This
//!   exclusive-bucket convention matches `tools/generate-compat-report.bb`'s
//!   own `pending-ledger-section` (`:diverge (- forms conform err-both
//!   timeout)`), which reads the same classification back off the
//!   committed `.golden`/`.mova` columns -- the two must always sum
//!   identically per area, since they classify the same 551 forms the
//!   same way from two independent code paths.
//! - **`Unreached`** -- every form after the `Timeout` form: no
//!   `##PENDING-BEGIN##` marker was ever observed for it, because the
//!   session ended before evaluation reached it. There is no evidence
//!   either way for an unreached form, so exactly like `Timeout` it is
//!   **not** folded into `Diverge` -- it is reported as its own count and
//!   never treated as debt (`Diverge`/`ErrBoth`) or as agreement
//!   (`Conform`).
//!
//! # Canonicalization lint
//!
//! Nothing mechanically stops a nondeterministic golden from being
//! authored (hash-iteration order, gensym names, wall-clock, randomness),
//! and a nondeterministic golden is worse than useless here: it can flip
//! between `Diverge` and `Conform` from one regeneration to the next for
//! reasons that have nothing to do with mova. `lint_nondeterminism` below
//! runs against every pending form (both the corpus source text and the
//! golden's `OK` payload) and hard-fails the test if it fires. See that
//! function's own doc for exactly what it catches and what it structurally
//! cannot.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::{Duration, Instant};

/// One line from a `.corpus` file that survived comment/blank filtering,
/// with its original 1-indexed line number (for messages and, later, for
/// a human to find the line to delete once it's promoted).
struct PendingForm {
    line: usize,
    src: String,
}

/// One line from a `.golden` file.
#[derive(Clone, PartialEq, Eq, Debug)]
enum Golden {
    Ok(String),
    Err(String),
}

/// One outcome of running a form as part of a whole-file mova session
/// (see module doc, "Session model"). `Timeout`/`Unreached` are
/// determined after the fact from which `##PENDING-*##` markers were (or
/// weren't) observed in the session's captured output before it ended.
enum MovaOutcome {
    Ok(String),
    Err,
    Timeout,
    Unreached,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Classification {
    Conform,
    ErrBoth,
    Diverge,
    Timeout,
    Unreached,
}

fn conformance_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/conformance")
}

fn pending_dir() -> PathBuf {
    conformance_dir().join("pending")
}

/// Must match `tests/conformance_test.rs::is_skippable` and
/// `tools/jvm-runner.clj`/`tools/jvm-pending-runner.clj`'s `skip-line?`
/// exactly, or corpus/golden line counts drift apart across every engine.
fn is_skippable(line: &str) -> bool {
    let trimmed = line.trim();
    trimmed.is_empty() || trimmed.starts_with(";;")
}

fn parse_corpus(path: &Path) -> Vec<PendingForm> {
    let text = fs::read_to_string(path).unwrap_or_else(|e| panic!("reading {path:?}: {e}"));
    text.lines()
        .enumerate()
        .filter(|(_, line)| !is_skippable(line))
        .map(|(i, line)| PendingForm { line: i + 1, src: line.to_string() })
        .collect()
}

fn parse_golden(path: &Path) -> Vec<Golden> {
    let text = fs::read_to_string(path).unwrap_or_else(|e| {
        panic!("reading {path:?}: {e} -- run `tools/gen-pending.sh` to (re)generate goldens")
    });
    text.lines()
        .map(|line| {
            if let Some(rest) = line.strip_prefix("OK\t") {
                Golden::Ok(rest.to_string())
            } else if let Some(rest) = line.strip_prefix("ERR\t") {
                Golden::Err(rest.to_string())
            } else {
                panic!("{path:?}: malformed pending golden line (want `OK\\t..` or `ERR\\t..`): {line:?}")
            }
        })
        .collect()
}

fn pending_areas() -> Vec<PathBuf> {
    let dir = pending_dir();
    let mut files: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("reading {dir:?}: {e}"))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("corpus"))
        .collect();
    files.sort();
    files
}

/// Tag prefixes for the three protocol lines `build_session_script`'s
/// generated program prints. Chosen to be implausible as a pending form's
/// own incidental `println` output; every line in the session's captured
/// combined output that doesn't start with one of these three is simply
/// not ours (JVM/mova startup noise, a stray print from a form under
/// test, a crash backtrace on stderr) and is ignored by the parser below
/// -- except that ALL of it stays in the captured file for a human to
/// read if `parse_session_output`'s all-`Unreached` sanity check fires.
const BEGIN_TAG: &str = "##PENDING-BEGIN##";
const OK_TAG: &str = "##PENDING-OK##";
const ERR_TAG: &str = "##PENDING-ERR##";

/// Per-FILE timeout budget (see module doc, "Session model" -- this
/// replaced a per-form timeout). Every normal, non-hanging file finishes
/// in well under a second regardless of form count, since it's one
/// process for the whole file rather than one cold start per form; the
/// per-form scaling term here is pure slack for a slow CI machine, not a
/// claim that forms are expected to be slow.
fn file_timeout(num_forms: usize) -> Duration {
    Duration::from_secs(10) + Duration::from_millis(150) * num_forms as u32
}

/// Escapes `src` for embedding as a mova/Clojure string literal.
fn escape_for_string_literal(src: &str) -> String {
    let mut out = String::with_capacity(src.len() + 2);
    for c in src.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out
}

/// Builds the ONE mova program that evaluates every form in `forms`, in
/// order, in a single session -- see the module doc's "Session model"
/// section for the full rationale (matching `tools/jvm-pending-runner.clj`'s
/// session model on the golden side; embedding each form as a string
/// literal read via `eval`/`read-string` rather than splicing raw source,
/// so a deliberately-malformed form can't corrupt the wrapper's own
/// parens; wrapping every form in `try`/`catch` so one throwing can't stop
/// the forms after it).
fn build_session_script(forms: &[PendingForm]) -> String {
    let mut out = String::from("(def pending-src [");
    for form in forms {
        out.push('"');
        out.push_str(&escape_for_string_literal(&form.src));
        out.push_str("\" ");
    }
    out.push_str("])\n");
    out.push_str(&format!(
        "(doseq [i (range (count pending-src))]\n\
        \x20 (println (str \"{BEGIN_TAG}\" i))\n\
        \x20 (try\n\
        \x20   (println (str \"{OK_TAG}\" i \"\\t\" (pr-str (eval (read-string (nth pending-src i))))))\n\
        \x20   (catch e\n\
        \x20     (println (str \"{ERR_TAG}\" i \"\\t\" (pr-str e))))))\n"
    ));
    out
}

/// Runs one area's entire form sequence as ONE `mova <script>` process.
/// stdout and stderr are merged into a single captured file (two
/// independent `File::try_clone` handles sharing one underlying fd --
/// the same trick a shell's `2>&1` uses) so a crash diagnostic on stderr
/// is never silently dropped. Polls `try_wait` and kills the child after
/// `file_timeout(forms.len())` rather than blocking on `wait()`, which
/// would hang this test process right along with a child stuck on mova's
/// known non-tail-`recur` bug.
fn run_session(binary: &str, forms: &[PendingForm], area: &str) -> Vec<MovaOutcome> {
    let script = build_session_script(forms);
    let dir = env::temp_dir();
    let pid = std::process::id();
    let script_path = dir.join(format!("mova-pending-{area}-{pid}.mova"));
    let out_path = dir.join(format!("mova-pending-{area}-{pid}.out"));
    fs::write(&script_path, &script)
        .unwrap_or_else(|e| panic!("writing session script {script_path:?}: {e}"));

    let out_file = fs::File::create(&out_path)
        .unwrap_or_else(|e| panic!("creating session output file {out_path:?}: {e}"));
    let stdout_handle =
        out_file.try_clone().unwrap_or_else(|e| panic!("cloning session output handle: {e}"));
    let stderr_handle =
        out_file.try_clone().unwrap_or_else(|e| panic!("cloning session output handle: {e}"));

    let mut child = Command::new(binary)
        .arg(&script_path)
        .stdin(Stdio::null())
        .stdout(Stdio::from(stdout_handle))
        .stderr(Stdio::from(stderr_handle))
        .spawn()
        .unwrap_or_else(|e| panic!("failed to spawn {binary} on {script_path:?}: {e}"));

    let timeout = file_timeout(forms.len());
    let start = Instant::now();
    loop {
        match child.try_wait() {
            Ok(Some(_status)) => break,
            Ok(None) => {
                if start.elapsed() >= timeout {
                    let _ = child.kill();
                    let _ = child.wait();
                    break;
                }
                std::thread::sleep(Duration::from_millis(10));
            }
            Err(e) => panic!("error waiting on {binary} for {area}: {e}"),
        }
    }

    let combined = fs::read_to_string(&out_path).unwrap_or_default();
    let _ = fs::remove_file(&script_path);
    let _ = fs::remove_file(&out_path);

    parse_session_output(&combined, forms.len(), area)
}

/// Recovers one `MovaOutcome` per form from a session's captured combined
/// output. A form with a matched `OK`/`ERR` marker got a real answer. A
/// form with a `BEGIN` marker but no matching `OK`/`ERR` was the one
/// in-flight when the session ended (killed after timeout, or crashed) --
/// `Timeout`. Every form after it, with no `BEGIN` marker at all, never
/// started -- `Unreached`.
fn parse_session_output(combined: &str, num_forms: usize, area: &str) -> Vec<MovaOutcome> {
    let mut began = vec![false; num_forms];
    let mut results: Vec<Option<MovaOutcome>> = (0..num_forms).map(|_| None).collect();

    for line in combined.lines() {
        if let Some(rest) = line.strip_prefix(BEGIN_TAG) {
            if let Ok(idx) = rest.trim().parse::<usize>() {
                if idx < num_forms {
                    began[idx] = true;
                }
            }
        } else if let Some(rest) = line.strip_prefix(OK_TAG) {
            if let Some((idx_str, payload)) = rest.split_once('\t') {
                if let Ok(idx) = idx_str.parse::<usize>() {
                    if idx < num_forms {
                        results[idx] = Some(MovaOutcome::Ok(payload.to_string()));
                    }
                }
            }
        } else if let Some(rest) = line.strip_prefix(ERR_TAG) {
            if let Some((idx_str, _payload)) = rest.split_once('\t') {
                if let Ok(idx) = idx_str.parse::<usize>() {
                    if idx < num_forms {
                        results[idx] = Some(MovaOutcome::Err);
                    }
                }
            }
        }
    }

    let outcomes: Vec<MovaOutcome> = results
        .into_iter()
        .zip(began)
        .map(|(res, saw_begin)| match res {
            Some(o) => o,
            None if saw_begin => MovaOutcome::Timeout,
            None => MovaOutcome::Unreached,
        })
        .collect();

    if num_forms > 0 && outcomes.iter().all(|o| matches!(o, MovaOutcome::Unreached)) {
        panic!(
            "{area}: every one of {num_forms} form(s) came back UNREACHED -- the session process \
             likely failed to start or crashed immediately; raw combined stdout+stderr:\n{combined}"
        );
    }

    outcomes
}

fn classify(golden: &Golden, mova: &MovaOutcome) -> Classification {
    match (golden, mova) {
        (_, MovaOutcome::Unreached) => Classification::Unreached,
        (_, MovaOutcome::Timeout) => Classification::Timeout,
        (Golden::Ok(g), MovaOutcome::Ok(m)) if g == m => Classification::Conform,
        (Golden::Err(_), MovaOutcome::Err) => Classification::ErrBoth,
        _ => Classification::Diverge,
    }
}

// ---------------------------------------------------------------------------
// Canonicalization lint
// ---------------------------------------------------------------------------

/// Splits Clojure/EDN source into reader-token-ish chunks: runs of
/// characters NOT in the delimiter set `()[]{}"'~@^`,;#` and not
/// whitespace. Good enough to recover call-position symbols like `rand`,
/// `clojure.core/rand`, or `System/currentTimeMillis` as single tokens
/// without a real reader -- it is not a real reader (doesn't understand
/// string contents, `#_` discard, etc.), which is exactly why the
/// output-shape checks below exist as the primary defense and this is
/// secondary.
fn reader_tokens(src: &str) -> Vec<&str> {
    src.split(|c: char| c.is_whitespace() || "()[]{}\"'~@^`,;#".contains(c))
        .filter(|s| !s.is_empty())
        .collect()
}

/// Nondeterministic-source calls that are essentially never safe to print
/// directly or transitively into a golden. Excludes `rand`/`rand-int`/
/// `rand-nth`: real pending corpora already use these legitimately, masked
/// behind a coarse predicate (`(number? (rand))`, `(int? (rand-int 10))`)
/// -- see `is_masked_by_coarse_predicate` below. Wall-clock and identity
/// sources stay banned unconditionally: unlike a random number, there's no
/// common idiom that turns "the current time" or "a random UUID" into a
/// meaningfully different, reproducible check.
const UNCONDITIONALLY_BANNED_CALLS: &[&str] = &[
    "shuffle",
    "gensym",
    "System/currentTimeMillis",
    "System/nanoTime",
    "Math/random",
    "random-uuid",
    "java.util.UUID/randomUUID",
    "java.util.Date",
];

/// `rand`/`rand-int`/`rand-nth` ARE checked, but only outside this
/// allowlist of outer call positions -- functions coarse enough that
/// their result is the same regardless of which random value fed them.
/// If a pending form's outer form is one of these, the inner `rand*` call
/// is not flagged.
const COARSE_PREDICATE_ALLOWLIST: &[&str] = &[
    "number?", "int?", "float?", "double?", "string?", "symbol?", "keyword?", "coll?",
    "sequential?", "associative?", "set?", "map?", "vector?", "list?", "seq?", "boolean?",
    "nil?", "some?", "class", "type", "count",
];

const CONDITIONALLY_BANNED_CALLS: &[&str] = &["rand", "rand-int", "rand-nth"];

/// The symbol in call position of `src`, if `src`'s first non-whitespace
/// character opens a list -- i.e. `(number? ...)` -> `Some("number?")`.
/// Best-effort/textual, matching `reader_tokens`'s own limits.
fn outer_call_symbol(src: &str) -> Option<&str> {
    let trimmed = src.trim_start();
    if !trimmed.starts_with('(') {
        return None;
    }
    reader_tokens(trimmed).first().copied()
}

/// A gensym/auto-gensym-shaped token: Clojure's syntax-quote auto-gensym
/// (`foo__123__auto__`) and plain `(gensym)` (`G__123`) both end in
/// `__<digits>` optionally followed by `__auto__`. A false positive here
/// would require a HAND-WRITTEN identifier matching that exact shape,
/// which no pending corpus does today (grepped: zero hits).
fn looks_gensym_shaped(payload: &str) -> bool {
    let bytes = payload.as_bytes();
    let mut i = 0;
    while i + 1 < bytes.len() {
        if bytes[i] == b'_' && bytes[i + 1] == b'_' {
            let mut j = i + 2;
            let digit_start = j;
            while j < bytes.len() && bytes[j].is_ascii_digit() {
                j += 1;
            }
            if j > digit_start {
                return true;
            }
        }
        i += 1;
    }
    false
}

/// Best-effort check for an un-canonicalized multi-entry map/set literal
/// in a golden's `OK` payload: flat (non-nested) `{...}` groups with more
/// than one entry, where the entries' keys are not already in ascending
/// order. Per `CONFORMANCE-GUARANTEE.md`'s canonicalization rule 2, an
/// author who wants a deterministic multi-entry map/set golden is
/// expected to wrap it in `(into (sorted-map) ...)`/`(sorted-set ...)`;
/// if the corpus form's OWN source text already mentions `sorted-map` or
/// `sorted-set`, this check is skipped entirely (the author already
/// canonicalized; sorted collections print in their own sort order, which
/// this same ascending check would otherwise correctly pass anyway, but
/// skipping avoids re-deriving that from print order alone).
///
/// Deliberately conservative in one direction: many small (<=8 entry)
/// literal maps/sets ARE printed in stable insertion order by real
/// Clojure's array-map/array-set representation, so an unsorted-looking
/// literal here is not proof of true nondeterminism -- it is a proxy for
/// "the author didn't canonicalize", which is the actionable finding
/// either way (wrap it, and the golden becomes robust to a future
/// representation change too).
fn has_unsorted_multi_entry_literal(payload: &str) -> Option<String> {
    let bytes = payload.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'{' {
            if let Some(close_rel) = payload[i + 1..].find(['{', '}']) {
                let close = i + 1 + close_rel;
                if bytes[close] == b'}' {
                    let inner = &payload[i + 1..close];
                    if let Some(reason) = unsorted_entries(inner) {
                        return Some(reason);
                    }
                }
            }
        }
        i += 1;
    }
    None
}

fn unsorted_entries(inner: &str) -> Option<String> {
    let entries: Vec<&str> = inner.split(", ").map(str::trim).filter(|s| !s.is_empty()).collect();
    if entries.len() < 2 {
        return None;
    }
    let keys: Vec<&str> = entries.iter().map(|e| e.split(' ').next().unwrap_or(e)).collect();
    if keys.windows(2).any(|w| w[0] > w[1]) {
        Some(format!("multi-entry {{...}} literal not in ascending key order: {inner:?}"))
    } else {
        None
    }
}

/// Runs every canonicalization check against one pending form. Returns
/// `Some(reason)` if the form should be rejected outright -- see the
/// module doc's "Canonicalization lint" section for the policy this
/// implements, and this function's own sub-checks for exactly what each
/// one catches. What it CANNOT catch, by construction: nondeterminism
/// hidden behind a coarse predicate this allowlist doesn't happen to
/// include, nondeterminism inside a NESTED map/set literal (the
/// unsorted-literal check only looks at flat, non-nested `{...}` spans),
/// and any nondeterministic value that happens to print identically on
/// every run by coincidence (e.g. a `rand` draw that always lands on the
/// same float would never be caught by any static check -- only running
/// the golden generator twice and diffing would, which is
/// `tools/gen-pending.sh`'s job, not this in-process lint's).
fn lint_nondeterminism(src: &str, golden: &Golden) -> Option<String> {
    let tokens = reader_tokens(src);
    for banned in UNCONDITIONALLY_BANNED_CALLS {
        if tokens.iter().any(|t| *t == *banned || t.rsplit('/').next() == Some(banned)) {
            return Some(format!(
                "form calls `{banned}`, a nondeterministic/wall-clock source with no safe masked usage"
            ));
        }
    }
    let masked = outer_call_symbol(src).map(|s| COARSE_PREDICATE_ALLOWLIST.contains(&s)).unwrap_or(false);
    if !masked {
        for banned in CONDITIONALLY_BANNED_CALLS {
            if tokens.iter().any(|t| *t == *banned || t.rsplit('/').next() == Some(banned)) {
                return Some(format!(
                    "form calls `{banned}` without wrapping it in a coarse predicate ({}); \
                     its printed value is not reproducible across golden regenerations",
                    COARSE_PREDICATE_ALLOWLIST.join("/")
                ));
            }
        }
    }
    if let Golden::Ok(payload) = golden {
        if payload.contains("#object[") {
            return Some(
                "golden payload contains `#object[` -- JVM object identity/hashcode is not stable across runs"
                    .to_string(),
            );
        }
        if looks_gensym_shaped(payload) {
            return Some(
                "golden payload contains a gensym-shaped token (`__<digits>`) -- gensym names are not stable across runs"
                    .to_string(),
            );
        }
        if !src.contains("sorted-map") && !src.contains("sorted-set") {
            if let Some(reason) = has_unsorted_multi_entry_literal(payload) {
                return Some(format!(
                    "{reason} -- wrap in `(into (sorted-map) ...)`/`(into (sorted-set) ...)` for a canonical golden"
                ));
            }
        }
    }
    None
}

// ---------------------------------------------------------------------------
// The test
// ---------------------------------------------------------------------------

#[test]
#[ignore = "known failure: 50 pending forms now match real Clojure, the ledger is stale"]
fn pending_conformance_ledger() {
    let binary = env!("CARGO_BIN_EXE_mova");
    let files = pending_areas();
    assert!(!files.is_empty(), "no *.corpus files found under tests/conformance/pending");

    let mut rejected: Vec<String> = Vec::new();
    let mut promotable: Vec<String> = Vec::new();
    let mut grand_total = 0usize;
    let mut grand_diverge = 0usize;
    let mut grand_err_both = 0usize;
    let mut grand_timeout = 0usize;
    let mut grand_unreached = 0usize;

    for corpus_path in &files {
        let area = corpus_path.file_stem().unwrap().to_string_lossy().into_owned();
        let golden_path = corpus_path.with_extension("golden");
        let forms = parse_corpus(corpus_path);
        let golden = parse_golden(&golden_path);
        assert_eq!(
            forms.len(),
            golden.len(),
            "{area}.corpus has {} form(s) but {area}.golden has {} line(s) -- \
             re-run `tools/gen-pending.sh {area}` to regenerate",
            forms.len(),
            golden.len()
        );

        // ONE session for the whole file (see module doc's "Session
        // model"), not one process per form -- a `def` on an earlier
        // line must be visible to a later line, matching the golden
        // side's own session model.
        let outcomes = run_session(binary, &forms, &area);
        assert_eq!(outcomes.len(), forms.len(), "{area}: outcome count didn't match form count");

        let mut diverge = 0usize;
        let mut err_both = 0usize;
        let mut timeout = 0usize;
        let mut unreached = 0usize;

        for ((form, expected), outcome) in forms.iter().zip(golden.iter()).zip(outcomes.iter()) {
            grand_total += 1;

            if let Some(reason) = lint_nondeterminism(&form.src, expected) {
                rejected.push(format!(
                    "{area}.corpus:{}: {}\n    REJECTED (canonicalization lint): {reason}",
                    form.line, form.src
                ));
                continue;
            }

            match classify(expected, outcome) {
                Classification::Conform => {
                    let Golden::Ok(v) = expected else { unreachable!() };
                    promotable.push(format!(
                        "{area}.corpus:{}: {}\n    both sides agree: OK\t{v}\n    \
                         ACTION: promote this form (with its golden) to tests/conformance/corpus/, \
                         then delete it from {area}.corpus/{area}.golden/{area}.mova",
                        form.line, form.src
                    ));
                }
                Classification::ErrBoth => err_both += 1,
                Classification::Diverge => diverge += 1,
                // TIMEOUT and UNREACHED are both EXCLUSIVE of DIVERGE
                // (see module doc) -- this must match
                // tools/generate-compat-report.bb's `pending-ledger-section`
                // bucket math exactly, since that script derives the same
                // classification independently from the committed
                // `.golden`/`.mova` columns and the two totals are meant
                // to be cross-checked against each other.
                Classification::Timeout => timeout += 1,
                // Unreached carries no evidence either way: not debt
                // (Diverge/ErrBoth), not agreement (Conform). Counted
                // only in its own bucket.
                Classification::Unreached => unreached += 1,
            }
        }

        println!(
            "pending[{area:<20}] {:>4} forms | {:>4} DIVERGE | {:>4} ERR-BOTH (needs error taxonomy) | \
             {:>3} TIMEOUT | {:>3} UNREACHED",
            forms.len(),
            diverge,
            err_both,
            timeout,
            unreached
        );

        grand_diverge += diverge;
        grand_err_both += err_both;
        grand_timeout += timeout;
        grand_unreached += unreached;
    }

    println!(
        "pending TOTAL: {grand_total} forms across {} area(s) | {grand_diverge} DIVERGE | \
         {grand_err_both} ERR-BOTH | {grand_timeout} TIMEOUT | {grand_unreached} UNREACHED",
        files.len()
    );

    if !rejected.is_empty() || !promotable.is_empty() {
        let mut msg = String::new();
        if !promotable.is_empty() {
            msg.push_str(&format!(
                "{} pending form(s) now CONFORM with real Clojure -- they are no longer pending:\n\n",
                promotable.len()
            ));
            msg.push_str(&promotable.join("\n\n"));
            msg.push('\n');
        }
        if !rejected.is_empty() {
            if !msg.is_empty() {
                msg.push('\n');
            }
            msg.push_str(&format!(
                "{} pending form(s) rejected by the canonicalization lint (see tests/conformance/pending/README.md):\n\n",
                rejected.len()
            ));
            msg.push_str(&rejected.join("\n\n"));
            msg.push('\n');
        }
        panic!("{msg}");
    }
}
