// Generated from completion_snippet.clj `known-snippets` (label, detail, insert-text, function-call?).
pub const SNIPPETS: &[(&str, &str, &str, bool)] = &[
    ("comment", "Insert comment block", "(comment\n  $0\n  )", true),
    ("comment-heading", "Insert comment header", ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n    ;; ${1:Namespace summary title}\n    ;;\n    ;; ${2:Brief description}\n;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n\n$0", false),
    ("comment-separator", "Insert comment separator", ";; ${1:Namespace summary title}\n;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n\n$0", false),
    ("rich-comment", "Insert rich comment block", "(comment\n      $0\n  #_())", true),
    ("rich-comment-rdd", "Insert rich comment rdd block", "#_{:clj-kondo/ignore [:redefined-var]}\n   (comment\n     $0\n   #_())", false),
    ("rich-comment-hotload", "Insert rich comment library hotload", "#_{:clj-kondo/ignore [:redefined-var]}\n    (comment\n      ;; Add-lib library for hot-loading\n      (require '[clojure.tools.deps.alpha.repl :refer [add-libs]])\n      (add-libs '{${1:domain/library-name} {:mvn/version \"${2:1.0.0}\"}$3})\n      $0\n    )", false),
    ("condp", "Insert condp", "(condp ${1:pred} ${2:expr}\n $0)", true),
    ("def", "Insert def", "(def ${1:name} $0)", true),
    ("def-", "Insert def private", "(def ^:private ${1:name} $0)", true),
    ("def-doc", "Insert def with docstring", "(def ${1:name}\n  \"${2:docstring}\"\n  $0)", true),
    ("defmethod", "Insert defmethod", "(defmethod ${1:name} ${2:match}\n [${3:args}]\n $0)", true),
    ("defmulti", "Insert defmulti", "(defmulti ${1:name} ${2:dispatch-fn})", true),
    ("defn", "Insert public defn", "(defn ${1:name} [$2]\n  $0)", true),
    ("defn-doc", "Insert public defn with docstring", "(defn ${1:name}\n  \"${2:docstring}\"\n   [${3:args}]\n  $0)", true),
    ("defn-", "Insert private defn", "(defn- ${1:name} [$2]\n  $0)", true),
    ("defprotocol", "Insert defprotocol", "(defprotocol ${1:Name}\n $0)", true),
    ("defrecord", "Insert defrecord", "(defrecord ${1:Name} [${2:fields}]\n ${3:Protocol}\n $0)", true),
    ("deftype", "Insert deftype", "(deftype ${1:Name} [${2:fields}]\n ${3:Protocol}\n $0)", true),
    ("fn", "Insert fn", "(fn [${1:arg-list}] $0)", true),
    ("for", "Insert for", "(for [${1:item} ${2:coll}]\n  $0)", true),
    ("if", "Insert if", "(if ${1:test-expr}\n ${2:then-expr}\n ${3:else-expr})", true),
    ("kwargs", "Insert keyword args", "& {:keys [${1:keys}] :or {${2:defaults}}}", false),
    ("let", "Insert let", "(let [${1:binding} ${2:value}])", true),
    ("letfn", "Insert letfn", "(letfn [(${1:name} [${2:args}]\n $0)])", true),
    ("ns", "Insert ns", "(ns ${1:name}\n  ${0:references})", true),
    ("ns-doc", "Insert ns with docstring", "(ns ${1:name}\n  \"${2:docstring}\"\n  $0)", true),
    ("require", "Insert ns :require", "(:require [${1:namespace}])$0", false),
    ("require-as", "Insert ns require with :as alias", "(:require [${1:namespace} :as ${2:alias}]$3)$0", false),
    ("require-refer", "Insert ns :require with :refer", "(:require [${1:namespace} :refer [$2]]$3)$0", false),
    ("require-rdd", "Insert require for rich comment experiments", "(require '[${1:namespace} :as ${2:alias}]$3)$0", false),
    ("req-as", "Insert single require dep :as alias", "[${1:namespace} :as ${2:alias}]", false),
    ("req-refer", "Insert single require dep with :refer", "[${1:namespace} :refer [$2]]", false),
    ("import", "Insert import", "(:import [${1:package}])", false),
    ("deps-alias", "Insert alias with extra path & deps", ":${1:category/name}\n    {:extra-paths [\"${2:path}\"]\n     :extra-deps {${3:deps-maven or deps-git}}}$0", false),
    ("deps-maven", "Insert maven dependency", "${1:domain/library-name} {:mvn/version \"${2:1.0.0}\"}$0", false),
    ("deps-git", "Insert git dependency", "${1:domain/library-name}\n       {:git/sha \"${2:git-sha-value}\"}$0", false),
    ("deps-git-tag", "Insert git tag dependency", "${1:domain/library-name}\n      {:git/tag \"${2:git-tag-value}\"\n       :git/sha \"${3:git-sha-value}\"}$0", false),
    ("deps-git-url", "Insert git URL dependency", "${1:domain/library-name}\n      {:git/url \"https://github.com/$1\"\n       :git/sha \"${2:git-sha-value}\"}$0", false),
    ("deps-local", "Insert local dependency", "${1:domain/library-name} {:local/root \"${2:/path/to/project/root}\"}$0", false),
    ("deftest", "Insert deftest clojure.test", "(deftest ${1:name}-test\n      (testing \"${2:Context of the test assertions}\"\n        (is (= ${3:assertion-values}))$4)) $0", false),
    ("testing", "Insert testing clojure.test", "(testing \"${1:Context of the test assertions}\"\n       $0)", false),
    ("is", "Insert is clojure.test", "(is (= ${1:assertion-values}))", false),
];
