#!/bin/bash
# tools/bootstrap-oracle.sh
#
# Materializes the conformance oracle -- real Clojure 1.13.0-alpha6, plus a
# checkout of its source at the pinned commit -- on a clean machine.
#
# WHY THIS EXISTS: this project's compatibility claim (CONFORMANCE-GUARANTEE.md)
# rests on differential testing against REAL Clojure, generated by shelling
# out to a pinned JVM (tools/gen-golden.bb, tools/gen-pending.sh,
# tools/jvm-runner.clj). Historically the pieces that make that runnable --
# a `clojure` invocation resolving the pinned version, and a checkout of the
# Clojure source used as the "spec of record" when a golden looks wrong --
# lived only in ad-hoc, session-scoped locations that do not survive past a
# single working session. That silently broke CONFORMANCE-GUARANTEE.md's
# rule 5 ("anyone can reproduce it in minutes on a clean checkout") and its
# "regenerate the goldens yourself" escape hatch for skeptics. This script
# is what makes both of those true again: one command, idempotent, that
# produces a `.oracle/` directory with everything gen-golden.bb,
# gen-pending.sh and a human skeptic need, from nothing but this repo and
# either network access or a local Clojure clone.
#
# THE PIN (single source of truth): tests/conformance/ORACLE.edn. This
# script asserts its :clojure-version agrees with the separate
# tests/conformance/CLOJURE_VERSION file (the bare one-line file every
# other tool in this repo already reads) on every run, so the two can never
# silently drift apart. See tests/conformance/ORACLE.md for the full
# explanation and the procedure for bumping the pin.
#
# WHAT GETS MATERIALIZED under $ORACLE_DIR (default: $REPO/.oracle, always
# gitignored -- override the location with the ORACLE_DIR env var):
#   deps/deps.edn         -- {:deps {org.clojure/clojure {:mvn/version <pinned>}}}
#                             `cd .oracle/deps && clojure -M -e '...'` is a real
#                             Clojure 1.13.0-alpha6 REPL/eval, exactly what
#                             tools/jvm-runner.clj and tools/jvm-pending-runner.clj
#                             shell out to (they build their own -Sdeps string
#                             inline, so this directory is for humans and any
#                             OTHER tool that wants the same resolved deps
#                             without reimplementing that string).
#   deps-async/deps.edn   -- same, plus org.clojure/core.async, mirroring
#                             EXACTLY the extra dep tools/gen-golden.bb's
#                             `jvm-golden`/`jvm-flow-golden` already add for
#                             async.corpus and flow.corpus (grepped from that
#                             file at the time this script was written --
#                             see tools/gen-golden.bb's `run-jvm-runner`).
#   clojure-src/          -- a git checkout of the Clojure repo at the PINNED
#                             COMMIT (not just the tagged version) -- the
#                             "spec of record" for reading src/jvm/clojure/lang/*.java,
#                             src/clj/clojure/core*.clj and
#                             test/clojure/test_clojure/ when a golden looks
#                             wrong and you don't want to trust this project's
#                             own paraphrase of what Clojure does.
#
# SOURCE STRATEGY for clojure-src, in order (each step logged so you can see
# which one was taken):
#   a) $CLOJURE_CLONE (optional; MOVA_CLOJURE_SRC_DIR is the same) is a git repo
#      that already contains the pinned commit -> `git worktree add --detach`
#      a worktree off it. This NEVER touches that clone's own HEAD or working
#      tree -- it only registers an additional, independent, detached
#      worktree at the pinned commit, so a dirty/on-master local clone is
#      left exactly as it was found.
#   b) otherwise, `git clone --filter=blob:none` the upstream repo fresh into
#      clojure-src and `git checkout --detach` the pinned commit (needs
#      network).
#   c) neither available -> hard-fail with an actionable message naming
#      exactly what to do (point CLOJURE_CLONE at a real clone, or get
#      network access).
#
# IDEMPOTENCE: every step first checks whether its target already exists in
# the correct state and skips re-doing it if so (re-running this script
# costs nothing beyond a few `git rev-parse`/file-diff checks and the JVM
# sanity eval). Nothing is ever force-deleted; a target found in the WRONG
# state is a hard failure naming what to fix by hand, never a silent
# overwrite.
#
# FLAGS:
#   (none)                  materialize (idempotently) + verify + print a
#                            human-readable summary to stdout
#   --check                 verify an existing .oracle WITHOUT creating or
#                            downloading anything; exit 1 if incomplete/wrong
#   --print-deps-dir         materialize+verify, then print ONLY the absolute
#                            path of .oracle/deps to stdout and exit 0
#   --print-src-dir          same, for .oracle/clojure-src
#   --print-deps-async-dir   same, for .oracle/deps-async
#
# CONTRACT for the --print-* flags (other tools rely on this): all
# human-readable logging goes to stderr; the LAST line of stdout is the bare
# absolute path and nothing else. Safe to use as `DIR=$(tools/bootstrap-oracle.sh
# --print-deps-dir)`.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ORACLE_EDN="$ROOT/tests/conformance/ORACLE.edn"
VERSION_FILE="$ROOT/tests/conformance/CLOJURE_VERSION"
ORACLE_DIR="${ORACLE_DIR:-$ROOT/.oracle}"
CLOJURE_CLONE="${CLOJURE_CLONE:-${MOVA_CLOJURE_SRC_DIR:-}}"

# core.async coordinate mirrored from tools/gen-golden.bb's `run-jvm-runner`
# (the literal string it appends to every JVM engine's -Sdeps map) -- kept
# as one named constant here so a future bump of that version only needs
# grepping this file and gen-golden.bb, not guessing.
CORE_ASYNC_VERSION="1.9.808-alpha1"

MODE="run"
case "${1:-}" in
  --check) MODE="check" ;;
  --print-deps-dir) MODE="print"; PRINT_TARGET="deps" ;;
  --print-src-dir) MODE="print"; PRINT_TARGET="clojure-src" ;;
  --print-deps-async-dir) MODE="print"; PRINT_TARGET="deps-async" ;;
  "") MODE="run" ;;
  *)
    echo "bootstrap-oracle.sh: unknown flag: $1" >&2
    echo "usage: $0 [--check | --print-deps-dir | --print-src-dir | --print-deps-async-dir]" >&2
    exit 1
    ;;
esac

# log: informational output. In --print-* mode this MUST go to stderr so
# stdout's last (and only) line stays the bare path (see module doc above).
# In the other two modes it goes to stdout since there's no such contract
# and a human is expected to read it directly.
log() {
  if [ "$MODE" = "print" ]; then
    echo "$@" >&2
  else
    echo "$@"
  fi
}

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

edn_str() {
  # Pulls `:key "value"` out of the flat, hand-written ORACLE.edn map --
  # good enough for this file's shape (one string-valued key per line),
  # deliberately not a general EDN parser.
  local key="$1"
  grep -E "^[[:space:]]*\{?[[:space:]]*:${key} " "$ORACLE_EDN" | head -1 | sed -E "s/^[[:space:]]*\{?[[:space:]]*:${key}[[:space:]]+\"([^\"]*)\".*/\1/"
}

[ -f "$ORACLE_EDN" ] || fail "pin file not found: $ORACLE_EDN"
[ -f "$VERSION_FILE" ] || fail "$VERSION_FILE not found (every other conformance tool reads this)"

PIN_VERSION="$(edn_str clojure-version)"
PIN_COMMIT="$(edn_str commit)"
PIN_REPO="$(edn_str repo)"
PIN_JDK="$(edn_str jdk-tested)"
[ -n "$PIN_VERSION" ] || fail "could not read :clojure-version out of $ORACLE_EDN"
[ -n "$PIN_COMMIT" ] || fail "could not read :commit out of $ORACLE_EDN"
[ -n "$PIN_REPO" ] || fail "could not read :repo out of $ORACLE_EDN"

VERSION_FILE_CONTENTS="$(tr -d '[:space:]' < "$VERSION_FILE")"
if [ "$PIN_VERSION" != "$VERSION_FILE_CONTENTS" ]; then
  fail "pin mismatch: $ORACLE_EDN says :clojure-version \"$PIN_VERSION\" but $VERSION_FILE contains \"$VERSION_FILE_CONTENTS\" -- these must always agree; fix whichever one is stale"
fi
log "pin OK: real Clojure $PIN_VERSION (commit $PIN_COMMIT) -- ORACLE.edn and CLOJURE_VERSION agree"

DEPS_DIR="$ORACLE_DIR/deps"
DEPS_ASYNC_DIR="$ORACLE_DIR/deps-async"
SRC_DIR="$ORACLE_DIR/clojure-src"

write_deps_edn() {
  # Idempotent by construction: content is fully determined by the pin, so
  # re-writing on every run is cheap and can never drift from a stale
  # earlier version.
  local dir="$1" content="$2"
  mkdir -p "$dir"
  local target="$dir/deps.edn"
  if [ -f "$target" ] && [ "$(cat "$target")" = "$content" ]; then
    log "  deps.edn already up to date: $target"
  else
    printf '%s\n' "$content" > "$target"
    log "  wrote: $target"
  fi
}

materialize_deps() {
  log "== deps (plain: just org.clojure/clojure $PIN_VERSION) =="
  write_deps_edn "$DEPS_DIR" "{:deps {org.clojure/clojure {:mvn/version \"$PIN_VERSION\"}}}"

  log "== deps-async (adds org.clojure/core.async $CORE_ASYNC_VERSION, for async.corpus/flow.corpus) =="
  write_deps_edn "$DEPS_ASYNC_DIR" "{:deps {org.clojure/clojure {:mvn/version \"$PIN_VERSION\"} org.clojure/core.async {:mvn/version \"$CORE_ASYNC_VERSION\"}}}"
}

materialize_src() {
  log "== clojure-src (spec of record at commit $PIN_COMMIT) =="

  if [ -d "$SRC_DIR/.git" ] || [ -f "$SRC_DIR/.git" ]; then
    local head
    head="$(git -C "$SRC_DIR" rev-parse HEAD 2>/dev/null || true)"
    if [ "$head" = "$PIN_COMMIT" ]; then
      log "  already present and at the pinned commit, skipping: $SRC_DIR"
      return 0
    else
      fail "$SRC_DIR exists but HEAD is $head, not the pinned $PIN_COMMIT -- remove $SRC_DIR by hand and re-run if you want it rebuilt (refusing to auto-delete)"
    fi
  fi

  if [ -e "$SRC_DIR" ]; then
    fail "$SRC_DIR exists and is not a git checkout -- remove it by hand and re-run"
  fi

  if [ -d "$CLOJURE_CLONE/.git" ] && git -C "$CLOJURE_CLONE" cat-file -e "${PIN_COMMIT}^{commit}" 2>/dev/null; then
    log "  strategy: (a) local clone at $CLOJURE_CLONE already has the pinned commit -- adding a detached worktree (does NOT touch that clone's HEAD or working tree)"
    mkdir -p "$ORACLE_DIR"
    git -C "$CLOJURE_CLONE" worktree prune >/dev/null 2>&1 || true
    git -C "$CLOJURE_CLONE" worktree add --detach "$SRC_DIR" "$PIN_COMMIT" >&2
  else
    log "  strategy: (a) skipped -- $CLOJURE_CLONE is not a git repo containing commit $PIN_COMMIT"
    log "  strategy: (b) cloning $PIN_REPO (blobless, then checking out the pinned commit) -- needs network"
    mkdir -p "$ORACLE_DIR"
    if git clone --filter=blob:none "$PIN_REPO" "$SRC_DIR" >&2 2>&1 && git -C "$SRC_DIR" checkout --detach "$PIN_COMMIT" >&2 2>&1; then
      log "  cloned and checked out $PIN_COMMIT"
    else
      rm -rf "$SRC_DIR"
      fail "strategy (c): no usable local clone at CLOJURE_CLONE=$CLOJURE_CLONE and the network clone of $PIN_REPO failed. Fix: either (1) point CLOJURE_CLONE at a git clone of $PIN_REPO that contains commit $PIN_COMMIT (fetch it there first if needed: git -C <clone> fetch origin $PIN_COMMIT), or (2) get network access to $PIN_REPO and re-run."
    fi
  fi
}

verify_src_commit() {
  [ -d "$SRC_DIR" ] || fail "$SRC_DIR does not exist (run without --check to materialize it)"
  local head
  head="$(git -C "$SRC_DIR" rev-parse HEAD 2>/dev/null || true)"
  [ -n "$head" ] || fail "$SRC_DIR is not a git checkout"
  [ "$head" = "$PIN_COMMIT" ] || fail "$SRC_DIR HEAD is $head, expected pinned commit $PIN_COMMIT"
  log "  verified: $SRC_DIR is at commit $PIN_COMMIT"
}

verify_deps_content() {
  local dir="$1" expected="$2"
  local target="$dir/deps.edn"
  [ -f "$target" ] || fail "$target does not exist (run without --check to materialize it)"
  [ "$(cat "$target")" = "$expected" ] || fail "$target does not match the pinned deps (found: $(cat "$target"))"
}

verify_jvm_runs() {
  [ -f "$DEPS_DIR/deps.edn" ] || fail "$DEPS_DIR/deps.edn missing, cannot sanity-check the JVM oracle"
  command -v clojure >/dev/null 2>&1 || fail "no 'clojure' CLI on PATH -- install the Clojure CLI tools (https://clojure.org/guides/install_clojure) to run the oracle"

  log "== sanity-checking the JVM oracle (cd $DEPS_DIR && clojure -M -e '(pr *clojure-version*)') =="
  local out
  if ! out="$(cd "$DEPS_DIR" && clojure -M -e '(pr *clojure-version*)' 2>&1)"; then
    fail "clojure -M -e failed to run in $DEPS_DIR; output was:\n$out"
  fi

  # *clojure-version* prints as {:major 1, :minor 13, :incremental 0, :qualifier "alpha6"};
  # cross-check major/minor/qualifier against the pinned "1.13.0-alpha6" string
  # rather than string-comparing the whole map, since :incremental isn't part
  # of the pin string.
  local expect_major expect_minor expect_qualifier
  expect_major="$(echo "$PIN_VERSION" | sed -E 's/^([0-9]+)\..*/\1/')"
  expect_minor="$(echo "$PIN_VERSION" | sed -E 's/^[0-9]+\.([0-9]+)\..*/\1/')"
  expect_qualifier="$(echo "$PIN_VERSION" | sed -E 's/^[0-9]+\.[0-9]+\.[0-9]+-(.*)$/\1/')"

  local got_major got_minor got_qualifier
  got_major="$(echo "$out" | grep -o ':major [0-9]*' | awk '{print $2}')"
  got_minor="$(echo "$out" | grep -o ':minor [0-9]*' | awk '{print $2}')"
  got_qualifier="$(echo "$out" | grep -o ':qualifier "[^"]*"' | sed -E 's/:qualifier "([^"]*)"/\1/')"

  if [ "$got_major" != "$expect_major" ] || [ "$got_minor" != "$expect_minor" ] || [ "$got_qualifier" != "$expect_qualifier" ]; then
    fail "JVM oracle reports the wrong Clojure version. Expected major=$expect_major minor=$expect_minor qualifier=$expect_qualifier (from pin $PIN_VERSION). Got raw output: $out"
  fi
  log "  verified: real Clojure reports major=$got_major minor=$got_minor qualifier=$got_qualifier (matches pin $PIN_VERSION)"
}

verify_all() {
  verify_deps_content "$DEPS_DIR" "{:deps {org.clojure/clojure {:mvn/version \"$PIN_VERSION\"}}}"
  verify_deps_content "$DEPS_ASYNC_DIR" "{:deps {org.clojure/clojure {:mvn/version \"$PIN_VERSION\"} org.clojure/core.async {:mvn/version \"$CORE_ASYNC_VERSION\"}}}"
  verify_src_commit
  verify_jvm_runs
}

print_path() {
  case "$PRINT_TARGET" in
    deps) echo "$DEPS_DIR" ;;
    clojure-src) echo "$SRC_DIR" ;;
    deps-async) echo "$DEPS_ASYNC_DIR" ;;
  esac
}

case "$MODE" in
  check)
    verify_all
    log ""
    log "OK: .oracle is complete and verified at $ORACLE_DIR"
    exit 0
    ;;
  print)
    materialize_deps
    materialize_src
    verify_all
    print_path
    exit 0
    ;;
  run)
    materialize_deps
    materialize_src
    verify_all
    log ""
    log "== summary =="
    log "  oracle root:        $ORACLE_DIR"
    log "  deps dir:            $DEPS_DIR"
    log "  deps-async dir:      $DEPS_ASYNC_DIR"
    log "  clojure-src dir:     $SRC_DIR"
    log "  verified commit:     $PIN_COMMIT"
    log "  verified version:    $PIN_VERSION (major=1 minor=13 qualifier=alpha6, jdk-tested=$PIN_JDK)"
    log "  clojure-src strategy: see the 'strategy:' lines above"
    log ""
    log "Other tools should locate these with:"
    log "  tools/bootstrap-oracle.sh --print-deps-dir"
    log "  tools/bootstrap-oracle.sh --print-deps-async-dir"
    log "  tools/bootstrap-oracle.sh --print-src-dir"
    exit 0
    ;;
esac
