#!/usr/bin/env bb
;; gen-golden.bb -- generates conformance goldens from REAL Clojure for every
;; tests/conformance/corpus/*.corpus file. Three engines:
;;   - jvm (DEFAULT, no `;;ENGINE` line needed): shells out once to a real
;;     JVM `clojure` process running `tools/jvm-runner.clj`, pinned to the
;;     exact version in tests/conformance/CLOJURE_VERSION -- see
;;     `engine-directive`/`jvm-golden` below.
;;   - jvm-flow (opt in via a `;;ENGINE jvm-flow` first line): the same idea,
;;     but via `tools/jvm-flow-runner.clj`, for corpora that need the REAL
;;     `clojure.core.async.flow` (a namespace nothing else here loads) --
;;     see `jvm-flow-golden` below and that file's own module doc.
;;   - bb (opt in via a `;;ENGINE bb` first line): evaluates forms in-process
;;     under babashka, for fast local previews only. NOT the default and
;;     never should be again: babashka runs on SCI, its own reimplementation
;;     of `clojure.core` with roughly 1.12-era semantics -- not real
;;     Clojure, and not the pinned 1.13.0-alpha6 in CLOJURE_VERSION. A
;;     conformance suite whose "real Clojure" goldens were generated by SCI
;;     is verifying mova against SCI, not against Clojure; every place the
;;     two disagree, the babashka-era goldens were silently encoding SCI's
;;     answer as ground truth. See compat/oracle-switch-report.md for the
;;     corpus lines that actually differed between the two when this
;;     default was flipped (2026-08-19).
;;
;; Corpus format: one top-level form per line. Lines starting with `;;` (after
;; leading whitespace) are comments and are skipped; blank lines are skipped.
;; Every other line must be exactly one s-expression.
;;
;; Session model: each corpus FILE is evaluated as ONE session -- forms in a
;; file may build on `def`s made earlier in the *same* file (a fresh
;; babashka namespace, or fresh `clojure` process, per file gives real
;; `def`/state isolation between files, matching how
;; tests/conformance_test.rs gives each corpus file its own fresh `Interp`).
;;
;; Output: for each non-comment/non-blank corpus line, appends one line to
;; the adjacent `.golden` file (same basename, `.golden` extension), in the
;; same order as the corpus lines (blanks/comments are not represented in
;; the golden file -- conformance_test.rs re-parses the corpus with the same
;; skip rules to re-align golden line i with corpus form i):
;;   OK<TAB><pr-str of the form's result>
;;   ERR<TAB><ExceptionSimpleName>         (the form threw)
;; The exception line carries the caught Throwable's simple class name
;; (e.g. `ArithmeticException`, `ExceptionInfo`, `CompilerException`), RAW
;; and unwrapped -- see tools/jvm-runner.clj/tools/jvm-flow-runner.clj's own
;; `eval-form`, and tools/jvm-pending-runner.clj (the original reference
;; implementation for this convention). NEVER the message text --
;; CONFORMANCE-GUARANTEE.md's canonicalization rule 6 compares exceptions
;; by occurrence and coarse kind only. tests/conformance_test.rs still
;; accepts a bare `ERR` line (kind unknown) for backward compatibility, but
;; every engine here now always emits the kind.
;;
;; Side-location mode: set the `GOLDEN_OUT_EXT` env var (e.g. `golden.jvm`)
;; to write output to `<basename>.<GOLDEN_OUT_EXT>` instead of overwriting
;; `<basename>.golden` -- lets a new engine's output be generated and
;; reviewed (diffed against the real goldens) before it replaces them. Used
;; exactly once, by hand, to produce compat/oracle-switch-report.md when the
;; default engine changed from bb to jvm; not needed for routine use.

(require '[clojure.string :as str]
         '[clojure.java.io :as io]
         '[clojure.java.shell :as shell])

(defn clojure-version
  "The pinned real-Clojure version, read from the ONE place it's written
  down: tests/conformance/CLOJURE_VERSION. Nothing in this script (or
  tools/jvm-runner.clj / tools/jvm-flow-runner.clj) hardcodes a version --
  bumping the oracle is a one-file edit."
  []
  (str/trim (slurp "tests/conformance/CLOJURE_VERSION")))

(defn corpus-files []
  (->> (file-seq (io/file "tests/conformance/corpus"))
       (filter #(and (.isFile %) (str/ends-with? (.getName %) ".corpus")))
       (sort-by #(.getName %))))

(defn golden-path [corpus-file]
  (let [ext (or (System/getenv "GOLDEN_OUT_EXT") "golden")]
    (str/replace (.getPath corpus-file) #"\.corpus$" (str "." ext))))

(defn skip-line?
  "True for a corpus line that isn't a form: blank, or a `;;`-prefixed
  comment (after leading whitespace)."
  [line]
  (let [trimmed (str/trim line)]
    (or (str/blank? trimmed)
        (str/starts-with? trimmed ";;"))))

;; `;;PRELUDE <clojure-code>` -- an OPT-IN, per-file setup form evaluated
;; once (in the file's fresh session-ns) before any of its real forms, but
;; itself produces NO golden line. Exists for corpus files that need a real
;; babashka `require` mova doesn't (e.g. async.corpus: mova's core.async
;; surface -- chan/>!!/<!!/go/... -- is global, but bb ships it under
;; `clojure.core.async` and needs `(require '[clojure.core.async :refer
;; [...]])` to bring those names into scope). Since a `;;PRELUDE` line still
;; starts with `;;`, `skip-line?` above (and `tests/conformance_test.rs`'s
;; identical `is_skippable`) already excludes it from `forms`/golden-line
;; counting on BOTH sides for free -- mova's side needs no prelude at all
;; (its names are global already), so nothing there has to change. Only the
;; FIRST such line in a file is honored (one prelude per file is enough for
;; every corpus we have; keeps this simple).
(defn prelude-form
  "The code text after `;;PRELUDE ` on the first line of `lines` that has
  that prefix (after trimming), or nil if none does."
  [lines]
  (some (fn [line]
          (let [trimmed (str/trim line)]
            (when (str/starts-with? trimmed ";;PRELUDE ")
              (subs trimmed (count ";;PRELUDE ")))))
        lines))

;; `;;ENGINE <name>` -- an OPT-IN, FILE-level directive (must be the FIRST
;; line of the corpus file) selecting which real-Clojure engine generates
;; that file's golden. Default (no `;;ENGINE` line, or `;;ENGINE jvm`) is
;; the `jvm-golden` path below -- a real JVM `clojure` process pinned to
;; CLOJURE_VERSION, running `tools/jvm-runner.clj`. `;;ENGINE jvm-flow`
;; shells out to the same kind of process but running
;; `tools/jvm-flow-runner.clj` instead, for the one corpus (flow.corpus)
;; that needs real `clojure.core.async.flow` loaded. `;;ENGINE bb` opts a
;; corpus file OUT of the real oracle and back into the old in-process
;; babashka `eval-form` path, for fast local iteration only -- see this
;; file's own module doc for why that can never be the default again.
;;
;; Both JVM engines shell out ONCE per corpus file, not per-form (JVM
;; startup is ~0.3-1s even warm, so this keeps a full file's cost to a
;; single process spawn). Each runner process prints exactly one
;; `OK<TAB><pr-str>` / `ERR<TAB><ExceptionSimpleName>` line per corpus form (in corpus order) to its
;; stdout; `jvm-golden`/`jvm-flow-golden` reuse that stdout verbatim as the
;; golden content, only checking the LINE COUNT matches (a content mismatch
;; there is a real bug in either the corpus or the runner, and should fail
;; loudly rather than write a desynced golden file).
(defn engine-directive
  "The engine name from a `;;ENGINE <name>` FIRST line of `lines`, or \"jvm\"
  (the default -- real Clojure, pinned via CLOJURE_VERSION) if the first
  line isn't such a directive."
  [lines]
  (let [first-line (str/trim (or (first lines) ""))]
    (if (str/starts-with? first-line ";;ENGINE ")
      (subs first-line (count ";;ENGINE "))
      "jvm")))

(defn run-jvm-runner
  "Shared shell-out machinery for both JVM engines: launches `clojure -M -e
  (load-file runner-path)` against `extra-deps` (a map literal string
  merged into `org.clojure/clojure {:mvn/version (clojure-version)}` --
  e.g. jvm-flow needs `org.clojure/core.async` too), with CORPUS_FILE set
  to `corpus-file`'s path, and returns its stdout as a string after
  checking exit status and line count. Any stderr from the JVM process
  (startup noise, or the runner's own per-form error detail) is surfaced
  on OUR stderr for debuggability, never mixed into the golden content."
  [runner-path corpus-file num-forms extra-deps-str]
  (let [deps-edn (format "{:deps {org.clojure/clojure {:mvn/version %s}%s}}"
                         (pr-str (clojure-version))
                         extra-deps-str)
        {:keys [exit out err]}
        (shell/sh "clojure"
                  "-Sdeps" deps-edn
                  "-M" "-e" (format "(load-file %s)" (pr-str runner-path))
                  :env (assoc (into {} (System/getenv)) "CORPUS_FILE" (.getPath corpus-file)))]
    (when (seq err)
      (binding [*out* *err*] (println err)))
    (when-not (zero? exit)
      (throw (ex-info (str runner-path " exited " exit " for " (.getName corpus-file)) {:exit exit})))
    (let [golden-lines (str/split-lines (str/trim-newline out))]
      (when-not (= (count golden-lines) num-forms)
        (throw (ex-info
                (format "%s: %s produced %d golden line(s) but corpus has %d form(s)"
                        (.getName corpus-file) runner-path (count golden-lines) num-forms)
                {:corpus-file (.getName corpus-file)})))
      (str out (when-not (str/ends-with? out "\n") "\n")))))

(defn jvm-golden
  "The default engine: a real JVM `clojure` process pinned to
  CLOJURE_VERSION, running `tools/jvm-runner.clj` (no extra deps beyond
  Clojure itself and `org.clojure/core.async`, which async.corpus's own
  `;;PRELUDE` needs -- see that file's module doc; every other corpus
  file simply never requires it)."
  [corpus-file num-forms]
  (run-jvm-runner "tools/jvm-runner.clj" corpus-file num-forms
                  " org.clojure/core.async {:mvn/version \"1.9.808-alpha1\"}"))

(defn jvm-flow-golden
  "The `;;ENGINE jvm-flow` engine (see tools/jvm-flow-runner.clj's own
  module doc): same shell-out shape as `jvm-golden`, but the runner
  unconditionally loads real `clojure.core.async.flow`."
  [corpus-file num-forms]
  (run-jvm-runner "tools/jvm-flow-runner.clj" corpus-file num-forms
                  " org.clojure/core.async {:mvn/version \"1.9.808-alpha1\"}"))

(defn eval-form
  "Evaluates one form's source text in the current (session) namespace,
  returning the golden line for it. On error, the golden line carries the
  caught exception's simple class name, RAW/outer and unwrapped, for
  format consistency with the jvm/jvm-flow engines (see this file's
  module doc and tools/jvm-pending-runner.clj, the reference
  implementation) -- even though this `bb` engine is a local-preview-only
  path, not the default oracle."
  [src]
  (try
    (let [v (load-string src)]
      (str "OK\t" (pr-str v)))
    (catch Throwable e
      (str "ERR\t" (.getSimpleName (class e))))))

(defn process-file [corpus-file idx]
  (let [lines (str/split-lines (slurp corpus-file))
        forms (remove skip-line? lines)
        out-path (golden-path corpus-file)]
    (case (engine-directive lines)
      "jvm"
      (let [golden-content (jvm-golden corpus-file (count forms))]
        (spit out-path golden-content)
        (println (format "  %-28s %3d forms -> %s  [engine: jvm, real clojure %s]"
                         (.getName corpus-file) (count forms) out-path (clojure-version))))

      "jvm-flow"
      (let [golden-content (jvm-flow-golden corpus-file (count forms))]
        (spit out-path golden-content)
        (println (format "  %-28s %3d forms -> %s  [engine: jvm-flow, real clojure.core.async.flow]"
                         (.getName corpus-file) (count forms) out-path)))

      "bb"
      (do
        ;; Fresh namespace per corpus file == fresh session, so `def`s in
        ;; one file never leak into the next (mirrors conformance_test.rs's
        ;; one `Interp::new()` per corpus file). Only meaningful for the bb
        ;; engine -- the jvm-flow engine above gets a fresh `clojure`
        ;; process per corpus file for free, so it needs no such reset.
        (let [session-ns (symbol (str "corpus-session-" idx))]
          (in-ns session-ns)
          (clojure.core/refer 'clojure.core))
        (when-let [prelude (prelude-form lines)]
          (load-string prelude))
        (let [golden-lines (mapv eval-form forms)]
          (spit out-path (str (str/join "\n" golden-lines) (when (seq golden-lines) "\n")))
          (println (format "  %-28s %3d forms -> %s" (.getName corpus-file) (count forms) out-path)))))))

(defn -main []
  (println "gen-golden: evaluating corpus/*.corpus -- default engine: real Clojure"
           (clojure-version) "(see tests/conformance/CLOJURE_VERSION);"
           "per-file `;;ENGINE jvm-flow`/`;;ENGINE bb` overrides honored")
  (let [files (corpus-files)]
    (when (empty? files)
      (println "no *.corpus files found under tests/conformance/corpus")
      (System/exit 1))
    (doseq [[idx f] (map-indexed vector files)]
      (process-file f idx))
    (println "done.")))

(-main)
