//! Concrete syntax tree: one `Vec<Node>` arena (preorder, root = id 0) plus a shared child index.
//!
//! # Analyzer API (see also `reader::parse`)
//! - `Cst::root()`, `node(id)`, `kind(id)`, `flags(id)`, `len()`.
//! - `children(id) -> &[NodeId]` (all children, incl. `Uneval`), `sig_children(id)` (skips `Uneval`).
//! - `span(id) -> (start, end)` byte offsets, `text(id) -> &str`, `pos(id) -> Pos` (kondo row/col).
//! - Tokens: `name(id)`/`ns(id)` SymIds of Symbol/Keyword (`SymId::NONE` when no ns). `Symbolic` (`##Inf`)
//!   keeps `Inf` in `name`. Numbers/strings/chars/regex: use `text(id)`; `string_content(id)` for the body.
//! - Meta: `Meta` node has children `[meta_form, target]`; `meta(id)`, `unwrap_meta(id)` -> innermost target.
//! - Wrappers (Quote, SyntaxQuote, Unquote, UnquoteSplicing, Deref, Var, Eval, Uneval) contain the operand
//!   as the LAST child; extra leading children are `Uneval` nodes (`'#_a b`). `Tagged` = `[tag, form]`.
//!   `NsMap` = `[Keyword(ns; AUTO flag for ::), Map]`. `ReaderCond` = `[List]`, flag `SPLICING` for `#?@`.
//! - `errors() -> &[ParseError]` (kondo messages). Positions: 1-based, cols in UTF-16 units, end-col just after.
//!
//! Positions: row u32, cols stored u16 and saturate at 65535 with `F_WIDE` set; `pos()` then recomputes exactly.

use crate::intern::SymId;

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, PartialOrd, Ord)]
#[repr(transparent)]
pub struct NodeId(pub u32);

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum Kind {
    Root,
    List,
    Vector,
    Map,
    Set,
    AnonFn,
    NsMap,
    ReaderCond,
    Quote,
    SyntaxQuote,
    Unquote,
    UnquoteSplicing,
    Deref,
    Var,
    Eval,
    Uneval,
    Meta,
    Tagged,
    Symbol,
    Keyword,
    String,
    Regex,
    Number,
    Char,
    Nil,
    True,
    False,
    Symbolic,
}

/// Flag: a column saturated at 65535; use `Cst::pos` for exact values.
pub const F_WIDE: u8 = 0x80;
/// Keyword flag: auto-resolved (`::kw`, `::a/kw`, `#::{}`).
pub const F_AUTO: u8 = 0x01;
/// ReaderCond flag: splicing `#?@`.
pub const F_SPLICING: u8 = 0x01;
/// Node flag: construct was unterminated / recovered from an error.
pub const F_ERROR: u8 = 0x02;
/// Analyzer-synthesized node (kondo `:clj-kondo.impl/generated`).
pub const F_GEN: u8 = 0x40;
/// Analyzer-synthesized node without source position (kondo `token-node` without meta).
pub const F_NOPOS: u8 = 0x20;
/// Synthetic symbol: skip local registration and usage (kondo `:clj-kondo/skip-reg-binding`, `mark-used`);
/// synthetic list: `:skip-analysis` (no var usage).
pub const F_SKIP: u8 = 0x10;
/// Node generated by a hook expansion with a derived location (kondo `:derived-location`).
pub const F_DERIVED: u8 = 0x08;
/// Number subtype, `flags & F_NUM_MASK`.
pub const F_NUM_MASK: u8 = 0x0f;
pub const NUM_INT: u8 = 1;
pub const NUM_RATIO: u8 = 2;
pub const NUM_FLOAT: u8 = 3;
pub const NUM_BIGINT: u8 = 4;
pub const NUM_BIGDEC: u8 = 5;
pub const NUM_INVALID: u8 = 6;

/// 32-byte node. Containers: `a` = offset into the child index. Tokens: `a` = name, `b` = ns.
#[derive(Clone, Copy, Debug)]
#[repr(C)]
pub struct Node {
    pub kind: Kind,
    pub flags: u8,
    pub col: u16,
    pub end_col: u16,
    _pad: u16,
    pub start: u32,
    pub end: u32,
    pub row: u32,
    pub end_row: u32,
    pub a: u32,
    pub b: u32,
}

impl Node {
    pub(crate) fn new(kind: Kind, flags: u8, start: u32, row: u32, col: u32) -> Node {
        let (c, w) = sat(col);
        Node { kind, flags: flags | w, col: c, end_col: 0, _pad: 0, start, end: start, row, end_row: row, a: 0, b: 0 }
    }
}

#[inline]
pub(crate) fn sat(col: u32) -> (u16, u8) {
    if col >= 0xffff {
        (0xffff, F_WIDE)
    } else {
        (col as u16, 0)
    }
}

/// Exact position of a node, kondo style.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Pos {
    pub row: u32,
    pub col: u32,
    pub end_row: u32,
    pub end_col: u32,
}

#[derive(Clone, PartialEq, Eq, Debug)]
pub struct ParseError {
    pub row: u32,
    pub col: u32,
    pub msg: String,
}

#[derive(Clone)]
pub struct Cst {
    pub(crate) src: Box<str>,
    pub(crate) nodes: Vec<Node>,
    /// Child lists: at `Node::a` sits the count, followed by that many child ids.
    pub(crate) index: Vec<NodeId>,
    pub(crate) errors: Vec<ParseError>,
    /// Lazy UTF-16 column checkpoints (every `CHK` bytes) for wide-line positions.
    pub(crate) wide: std::sync::OnceLock<Box<[u32]>>,
}

const CHK: usize = 256;

impl Cst {
    #[inline]
    pub fn root(&self) -> NodeId {
        NodeId(0)
    }
    #[inline]
    pub fn len(&self) -> usize {
        self.nodes.len()
    }
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }
    #[inline]
    pub fn src(&self) -> &str {
        &self.src
    }
    #[inline]
    pub fn node(&self, id: NodeId) -> &Node {
        &self.nodes[id.0 as usize]
    }
    #[inline]
    pub fn kind(&self, id: NodeId) -> Kind {
        self.node(id).kind
    }
    #[inline]
    pub fn flags(&self, id: NodeId) -> u8 {
        self.node(id).flags
    }
    #[inline]
    pub fn errors(&self) -> &[ParseError] {
        &self.errors
    }
    /// Approximate heap bytes used (nodes + child index + source).
    pub fn heap_bytes(&self) -> usize {
        self.nodes.capacity() * 32 + self.index.capacity() * 4 + self.src.len()
    }

    #[inline]
    pub fn is_container(k: Kind) -> bool {
        (k as u8) <= Kind::Tagged as u8
    }

    pub fn children(&self, id: NodeId) -> &[NodeId] {
        let n = self.node(id);
        if !Self::is_container(n.kind) {
            return &[];
        }
        let a = n.a as usize;
        let cnt = self.index[a].0 as usize;
        &self.index[a + 1..a + 1 + cnt]
    }

    /// Children without `Uneval` nodes.
    pub fn sig_children(&self, id: NodeId) -> impl Iterator<Item = NodeId> + '_ {
        self.children(id).iter().copied().filter(move |&c| self.kind(c) != Kind::Uneval)
    }

    #[inline]
    pub fn span(&self, id: NodeId) -> (u32, u32) {
        let n = self.node(id);
        (n.start, n.end)
    }
    #[inline]
    pub fn text(&self, id: NodeId) -> &str {
        let n = self.node(id);
        self.src.get(n.start as usize..n.end as usize).unwrap_or("")
    }

    /// Symbol/Keyword/Symbolic name part (`SymId::NONE` for other kinds).
    #[inline]
    pub fn name(&self, id: NodeId) -> SymId {
        let n = self.node(id);
        match n.kind {
            Kind::Symbol | Kind::Keyword | Kind::Symbolic => SymId(n.a),
            _ => SymId::NONE,
        }
    }
    /// Symbol/Keyword namespace part (`SymId::NONE` if none).
    #[inline]
    pub fn ns(&self, id: NodeId) -> SymId {
        let n = self.node(id);
        match n.kind {
            Kind::Symbol | Kind::Keyword => SymId(n.b),
            _ => SymId::NONE,
        }
    }

    /// Body of a String/Regex node without quotes (raw, escapes not decoded).
    pub fn string_content(&self, id: NodeId) -> &str {
        let n = self.node(id);
        let t = self.text(id);
        let open = if n.kind == Kind::Regex { 2 } else { 1 };
        let closed = t.len() >= open + 1 && t.ends_with('"') && n.flags & F_ERROR == 0;
        t.get(open..t.len() - closed as usize).unwrap_or("")
    }

    /// For a `Meta` node: `(meta_form, target)`.
    pub fn meta(&self, id: NodeId) -> Option<(NodeId, NodeId)> {
        if self.kind(id) != Kind::Meta {
            return None;
        }
        let c = self.children(id);
        let t = *c.iter().rev().find(|&&x| self.kind(x) != Kind::Uneval)?;
        let m = *c.iter().find(|&&x| self.kind(x) != Kind::Uneval && x != t)?;
        Some((m, t))
    }

    /// Strip any number of `Meta` wrappers; returns the innermost target.
    pub fn unwrap_meta(&self, mut id: NodeId) -> NodeId {
        while let Some((_, t)) = self.meta(id) {
            id = t;
        }
        id
    }

    /// Child list as `(start, count)` into the shared index; stays valid while nodes are appended.
    #[inline]
    pub fn kids(&self, id: NodeId) -> (u32, u32) {
        let n = self.node(id);
        if !Self::is_container(n.kind) {
            return (0, 0);
        }
        (n.a + 1, self.index[n.a as usize].0)
    }
    #[inline]
    pub fn kid(&self, r: (u32, u32), i: u32) -> NodeId {
        self.index[(r.0 + i) as usize]
    }
    /// Child `i` (0-based) of a container, if any.
    #[inline]
    pub fn nth(&self, id: NodeId, i: u32) -> Option<NodeId> {
        let r = self.kids(id);
        if i < r.1 {
            Some(self.kid(r, i))
        } else {
            None
        }
    }
    /// Append a synthetic container copying the position of `like` (or no position when `None`).
    pub fn push_container(&mut self, kind: Kind, like: Option<NodeId>, kids: &[NodeId], extra_flags: u8) -> NodeId {
        let mut n = match like {
            Some(l) => *self.node(l),
            None => Node::new(kind, F_NOPOS, 0, 0, 0),
        };
        n.kind = kind;
        n.flags = (n.flags & (F_WIDE | F_NOPOS)) | extra_flags;
        if like.is_none() {
            n.flags |= F_NOPOS;
        }
        let at = self.index.len() as u32;
        self.index.push(NodeId(kids.len() as u32));
        self.index.extend_from_slice(kids);
        n.a = at;
        n.b = 0;
        self.nodes.push(n);
        NodeId(self.nodes.len() as u32 - 1)
    }
    /// Append a synthetic Symbol/Keyword token copying the position of `like`.
    pub fn push_token(&mut self, kind: Kind, like: Option<NodeId>, name: SymId, ns: SymId, extra_flags: u8) -> NodeId {
        let mut n = match like {
            Some(l) => *self.node(l),
            None => Node::new(kind, F_NOPOS, 0, 0, 0),
        };
        n.kind = kind;
        n.flags = (n.flags & (F_WIDE | F_NOPOS)) | extra_flags;
        if like.is_none() {
            n.flags |= F_NOPOS;
        }
        n.a = name.0;
        n.b = ns.0;
        self.nodes.push(n);
        NodeId(self.nodes.len() as u32 - 1)
    }
    /// Clone of a node record with replaced flags bit set (used to mark generated nodes).
    pub fn push_clone(&mut self, id: NodeId, set_flags: u8) -> NodeId {
        let mut n = *self.node(id);
        n.flags |= set_flags;
        self.nodes.push(n);
        NodeId(self.nodes.len() as u32 - 1)
    }
    /// Replace the child list of a container (appends a new list to the index).
    pub fn set_children(&mut self, id: NodeId, kids: &[NodeId]) {
        let at = self.index.len() as u32;
        self.index.push(NodeId(kids.len() as u32));
        self.index.extend_from_slice(kids);
        self.nodes[id.0 as usize].a = at;
    }
    #[inline]
    pub fn has_pos(&self, id: NodeId) -> bool {
        self.node(id).flags & F_NOPOS == 0
    }
    #[inline]
    pub fn is_gen(&self, id: NodeId) -> bool {
        self.node(id).flags & F_GEN != 0
    }

    /// Exact column at byte `p` in O(CHK) via lazily built checkpoints.
    fn wide_col(&self, p: usize) -> u32 {
        let b = self.src.as_bytes();
        let chk = self.wide.get_or_init(|| {
            let mut v = Vec::with_capacity(b.len() / CHK + 1);
            let mut col = 1u32;
            for (i, &c) in b.iter().enumerate() {
                if i % CHK == 0 {
                    v.push(col);
                }
                col = if c == b'\n' || c == b'\r' { 1 } else { col + utf16_width(c) };
            }
            v.into_boxed_slice()
        });
        let p = p.min(b.len());
        let i = (p / CHK).min(chk.len().saturating_sub(1));
        let base = i * CHK;
        if chk.is_empty() || base > p {
            return col_at(b, p);
        }
        let mut col = chk[i];
        for &c in &b[base..p] {
            col = if c == b'\n' || c == b'\r' { 1 } else { col + utf16_width(c) };
        }
        col
    }

    /// Exact kondo position (row, col, end-row, end-col) of a node.
    pub fn pos(&self, id: NodeId) -> Pos {
        let n = self.node(id);
        if n.flags & F_WIDE == 0 {
            return Pos { row: n.row, col: n.col as u32, end_row: n.end_row, end_col: n.end_col as u32 };
        }
        Pos {
            row: n.row,
            col: self.wide_col(n.start as usize),
            end_row: n.end_row,
            end_col: self.wide_col(n.end as usize),
        }
    }
}

/// Exact 1-based UTF-16 column of byte offset `p` (slow: scans back to line start).
pub(crate) fn col_at(b: &[u8], p: usize) -> u32 {
    let p = p.min(b.len());
    let ls = b[..p].iter().rposition(|&c| c == b'\n' || c == b'\r').map_or(0, |i| i + 1);
    let mut col = 1u32;
    for &c in &b[ls..p] {
        col += utf16_width(c);
    }
    col
}

/// UTF-16 units contributed by one UTF-8 byte (lead bytes count, continuations 0).
#[inline(always)]
pub(crate) fn utf16_width(c: u8) -> u32 {
    if c < 0x80 {
        1
    } else if c < 0xC0 {
        0
    } else if c < 0xF0 {
        1
    } else {
        2
    }
}
